### ISSUE TITLE
Most command fail with <type 'int'> is not allowed for map key

### ISSUE THREAD

**Issue by Zorilixer** [alxchk/pupy#22]
Most commands fail with `<type 'int'> is not allowed for map key`.
Seems to be only related on the Pupy host.

Examples:
```
>> run ls
[-] <type 'int'> is not allowed for map key
>> netstat
2020-02-24 13:39:53,090| <type 'int'> is not allowed for map key
Traceback (most recent call last):
  File "/home/user/pupy/pupy/modules/netstat.py", line 42, in run
    'pupyps', 'families'
  File "/home/user/pupy/pupy/pupylib/PupyClient.py", line 274, in remote_const
    remote_variable = obtain(getattr(self.conn.modules[module], variable))
  File "/home/user/pupy/pupy/pupylib/utils/rpyc_utils.py", line 63, in obtain
    return safe_obtain(proxy)
  File "/home/user/pupy/pupy/pupylib/utils/rpyc_utils.py", line 51, in safe_obtain
    data = msgpack.loads(data)
  File "/home/user/.local/lib/python2.7/site-packages/msgpack/fallback.py", line 129, in unpackb
    ret = unpacker._unpack()
  File "/home/user/.local/lib/python2.7/site-packages/msgpack/fallback.py", line 666, in _unpack
    "%s is not allowed for map key" % str(type(key))
ValueError: <type 'int'> is not allowed for map key
```

Any ideas?  
Maybe related to wrong Python package/module versions? Is there somewhere a pip-freeze file for reference?

Steps to reproduce:
1. `git checkout -f b1e2b72`
2. `client/build-docker.sh windows sources`
3. `pupy/pupysh.sh`

Build environment: Debian 9.7 using `build-docker.sh` for revision b1e2b72. But also tested on older versions - no success, same error.
Pupy host: Debian 9.7
Pupy client: Windows 10 1803 x64.
```
>> info
hostname       win10vm                                                                             
user           WIN10VM\user                                                                        
release        10                                                                                  
version        10.0.17763                                                                          
cmdline        pupyx64d.x4QMEe.exe                                                                 
os_arch        AMD64                                                                               
proc_arch      64bit                                                                               
pid            2444                                                                                
exec_path      C:\temp\pupyx64d.x4QMEe.exe                                                         
cid            000000008ba4f97c                                                                    
address        192.168.56.101                                                                      
macaddr        xxx                                                                   
revision       b1e2b729                                                                            
node           0800278caf68                                                                        
debug_logfile  c:\users\user\appdata\local\temp\pupy-ckrr5p\pupy-client-1582456462-2444-debug.log  
native         True                                                                                
proxy          wpad                                                                                
external_ip    ?                                                                                   
uac_lvl        2/3                                                                                 
intgty_lvl     Medium                                                                              
local_adm      Yes                                                                                 
launcher       connect                                                                             
launcher_args  -t ssl -c 192.168.56.106:8443 --host 172.18.0.2:8443                                
platform       windows/amd64                                 
```

**Comment by alxchk** [comment]
Yeah, msgpack updated. Looks like they remove python2 support in CAPI. Will force 0.6.2.

**Comment by Zorilixer** [comment]
Yes, msgpack==0.6.2 fixed it, works.

Thanks very much! Quick and fast solution (commit b87c6a3f43f31b662f65aa944cb07c4637c5bca4).
