### ISSUE TITLE
No handlers could be found for logger "pupy.network"

### ISSUE THREAD

**Issue by ghost** [alxchk/pupy#7]
I get this error when I launch pupygen.py or pupysh.py

`No handlers could be found for logger "pupy.network"
Traceback (most recent call last):
  File "pupygen.py", line 14, in <module>
    from pupylib.utils.network import get_listener_ip, get_listener_port
  File "/usr/share/pupy/pupy/pupylib/__init__.py", line 18, in <module>
    from PupyService import *
  File "/usr/share/pupy/pupy/pupylib/PupyService.py", line 28, in <module>
    from pupylib.PupyCredentials import Credentials
  File "/usr/share/pupy/pupy/pupylib/PupyCredentials.py", line 17, in <module>
    from network.lib.picocmd.ecpv import ECPV
  File "/usr/share/pupy/pupy/network/lib/picocmd/__init__.py", line 2, in <module>
    from .client import *
  File "/usr/share/pupy/pupy/network/lib/picocmd/client.py", line 31, in <module>
    from ecpv import ECPV
  File "/usr/share/pupy/pupy/network/lib/picocmd/ecpv.py", line 11, in <module>
    from Crypto.Hash import SHA1, SHA3_256, SHA3_512
  File "/usr/share/pupy/local/lib/python2.7/site-packages/Crypto/Hash/SHA1.py", line 23, in <module>
    from Crypto.Util._raw_api import (load_pycryptodome_raw_lib,
  File "/usr/share/pupy/local/lib/python2.7/site-packages/Crypto/Util/_raw_api.py", line 32, in <module>
    from Crypto.Util.py3compat import byte_string
ImportError: cannot import name byte_string
`

**Comment by alxchk** [comment]
This is likely because pycrypto/pycryptodome conflict.

Try 
```
pip install --upgrade --force-reinstall pycryptodome
```

**Comment by ghost** [comment]
Ok thanks for your help.
It worked correctly.
